/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculator_TYPES_H
#define calculator_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace example {

class ExampleStructure;

typedef struct _ExampleStructure__isset {
  _ExampleStructure__isset() : id(false), message(false) {}
  bool id :1;
  bool message :1;
} _ExampleStructure__isset;

class ExampleStructure {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  ExampleStructure(const ExampleStructure&);
  ExampleStructure& operator=(const ExampleStructure&);
  ExampleStructure() : id(0), message() {
  }

  virtual ~ExampleStructure() throw();
  int32_t id;
  std::string message;

  _ExampleStructure__isset __isset;

  void __set_id(const int32_t val);

  void __set_message(const std::string& val);

  bool operator == (const ExampleStructure & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const ExampleStructure &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ExampleStructure & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ExampleStructure& obj);
};

void swap(ExampleStructure &a, ExampleStructure &b);

} // namespace

#endif
