/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculator_constants.h"

namespace example {

const calculatorConstants g_calculator_constants;

calculatorConstants::calculatorConstants() {
}

} // namespace

